### ISSUE TITLE
Change edf dependency from edflib to pyEDF?

### ISSUE THREAD

**Issue by scott-huberty** [mne-tools/mne-bids#1002]
Seems like there is a long unresolved [bug](https://github.com/cleemesser/python-edf/issues/1) in the `edflib` library that prevents many users from being able to install the library. This will cause an error in the `mne_bids.write_raw_bids` function if the user sets the format argument to `EDF`.

It also appears that there have been suggestions of [merging](https://github.com/cleemesser/python-edf/issues/2) `edf` file support efforts with the [pyedflib](https://github.com/holgern/pyedflib) library which appears to be more actively supported. Might it be a good idea to switch the `mne_bids` dependency from `edflib` to `pyedflib`? That is unless someone fixes the broken packaging in `edflib` (although its been 2 years now with no fix).

**Comment by adam2392** [comment]
Don't we use EDFlib-Python?

**Comment by scott-huberty** [comment]
> Don't we use EDFlib-Python?

Sorry.. Seemed to be a case of confusing two similarly named packages.

just FYI, the confusions stemmed from this: If the user doesn't have `EDFlib-Python` installed,  `mne_bids.write_raw_bids` will return the error `the EDFlib module is needed, but it could not be imported.` (the error actually stems from a check in `mne` `_edf.py`). 

This might prompt a user who is unfamiliar with `EDFlib-Python` (i.e. myself) to try `pip install EDFlib`. Of course that doesn't install `EDFlib-Python`, but installs [edflib](https://pypi.org/project/edflib/)..

Just wanted to share in case anyone wanted to try to make that error more specific for future users.

**Comment by larsoner** [comment]
> This might prompt a user who is unfamiliar with EDFlib-Python (i.e. myself) to try pip install EDFlib. Of course that doesn't install EDFlib-Python, but installs edflib (or rather, tries to install..)..

I installed the wrong thing, too, when I was debugging.

@scott-huberty could you make a PR to fix the error message to be more explicit that `EDFlib-Python` needs to be installed? This should lead users to `pip install EDFlib-Python` rather than the wrong thing(s).

We also don't install edflib-python in our installers, but I've started the process to fix that in https://github.com/conda-forge/mne-feedstock/pull/94

**Comment by scott-huberty** [comment]
@larsoner it is validating to hear that I'm not the only one who mixed those two libraries up!

Sure, should hopefully be as simple as a small revision to `mne.utils.check._soft_import()` to be more verbose in the case of `EDFlib`. I will test this in the next week or two.

https://github.com/mne-tools/mne-python/blob/aa4118655e70b57d99262aad70d4fe38ea6ecd63/mne/utils/check.py#L321-L342

**Comment by larsoner** [comment]
Yeah I think you might need to add a parameter and change the string along the lines of:
```
def _soft_import(name, purpose, strict=True, pip_name=None):
    pip_name = name if pip_name is None else pip_name
    ...
    ... f'... {pip_name} ...'
```
Because this is the first time we've really needed to differentiate between the module installation name and the import name.

But really there will probably be a finite set of these that we actually care about, and `scikit-learn` is another one that I can think of offhand, so maybe we want to keep the signature the same and just do:
```
    pip_name = dict(
        sklearn='scikit-learn',
        edflib='EDFlib-Python',
    )[name]
```

**Comment by larsoner** [comment]
I'll close this in favor of #10562, since it seems in the end like we "just" need better "how to fix this" instructions, and that issue is titled properly for it

**Comment by larsoner** [comment]
(and FYI there is also a related issue https://github.com/mne-tools/mne-python/issues/9883 about which EDF dependency we should actually use)
