### ISSUE TITLE
Replace pandas dependency with custom private functions

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#110]
the pandas dependency is not used very much ... mainly for reading and writing csv files. And in some instances, replacing cells within a csv file.

We should be able to replace this dependency with a set of private functions.

**Comment by sappelhoff** [comment]
given #99, I think we should maybe keep pandas - it would be too much of an unnecessary hassle to replace the functions with custom code. Other opinions?

**Comment by monkeyman192** [comment]
after my work on #99 it actually made me think better of removing the pandas dependency as it can give us better control.
My suggestion is to essentially move to using numpy instead of pandas as numpy is already required and has functions for reading and writing tsv files.
I'll have a think and play with how simple replacing some of the pandas functions with numpy functions would be

**Comment by jasmainak** [comment]
you have my +100 and blessing for removing pandas. The less dependencies, the better!
