### ISSUE TITLE
weird CI failure in schedules run: scipy build broken, "setuptools" missing

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1107]
This is the run in question: https://github.com/mne-tools/mne-bids/actions/runs/3616926118

We got:

> ImportError: The `scipy` install you are using seems to be broken, (extension modules cannot be imported), please try reinstalling.

And:

> ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.

:shrug: I have no idea where these are coming from, but I have observed them more and more often in occasional runs. Anyone got an idea?

**Comment by larsoner** [comment]
For the SciPy `libffi.so.7` problem, maybe this happened because `ubuntu-latest` changed from 20.04 to 20.10, and you're using an old SciPy (1.2.0) without upgrading? I'd try upgrading SciPy to see if that fixes that problem

For the 3.7 problem, I'd try bumping to Python 3.8 as your minimum. It's possible somehow a dependency (setuptools?) is not happy with you using 3.7, though I'm not sure...

I'll open a quick PR with these ideas to see how wrong they are
