### ISSUE TITLE
Cleanup the namespace and the arguments

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-bids#190]
While reviewing the module, I noticed that there isn't a clean namespace. In prep for adding pipelines to the module, we should restructure it. 
- We should have the read and write functions live in `mne_bids.io`. this would be either with the function signature there, or having the name called from the io `__init__` file. 
- ~~We have `make_bids_basename` but it does not include the bids_directory base. I think we should include it in the function signature and have the full basename path.~~
- ~~Afterwards we could then remove bids_root from the `read_raw_bids` given that the basename would now contain this information~~

**Comment by sappelhoff** [comment]
@teonbrooks you suggested to change [`make_bids_basename`](https://github.com/mne-tools/mne-bids/blob/87a7737da859863a55829fbfe3bb1371b6d1b794/mne_bids/utils.py#L106) so that it takes an additional argument `output_path` (or `bids_root` or similar). 

Doing this would allow us to remove the `output_path` argument from [`write_raw_bids`](https://github.com/mne-tools/mne-bids/blob/87a7737da859863a55829fbfe3bb1371b6d1b794/mne_bids/mne_bids.py#L540). 

Trying to implement this request I realized that it would involve overhauling the whole package, because our test suite as well as all the single BIDS creator functions depend on the separate passing of the `bids_basename` and the path to the BIDS directory.

I think it makes intuitively sense to separate the path that goes to the BIDS directory (which is completely arbitrary) from the path within the BIDS directory (which is completely deterministic and principled).

The only benefit of combining this separation would be one argument less in our `write_raw_bids` function --- however, this is not a real benefit to the user, because the user will have to specify the `output_path` in any case

I suggest we keep the separation of path handling between **bids internal paths** and **arbitrary paths to a BIDS directory**.

**Comment by jasmainak** [comment]
yes, please let's be pragmatic. There are always cleaner and better ways to do things but we should move forward not sideways.

**Comment by sappelhoff** [comment]
Following our discussion, I updated Teon's issue. The intermediate smaller fixes I made while trying to address the original issue are still very valuable and all in #191. I think these should be merged, after a review (@jasmainak  ?)

I will now make a new PR to restructure our IO module --> essentially making it a sub-package.
