### ISSUE TITLE
Feature Request: Allow MNE-BIDS to deduce "durations" from onset and offset of trigger value in events

### ISSUE THREAD

**Issue by hstojic** [mne-tools/mne-bids#224]
I have event objects that are numpy arrays with three columns: `event_sample | previous_event_id | event_id`

For example:
```python
array([[  4648,      0,      1],
       [  4889,      1,      0],
       [  5320,      0,      2],
       [  5561,      2,      0],
       [  6573,      0,      4],
       [  7474,      4,      0]])
```
If I pass this object to `write_raw_bids` together with `event_id` following events file is produced:
```python
onset	duration	trial_type	value	sample
7.746	0.0	probe	1	4648
8.148	0.0	n/a	0	4889
8.866	0.0	stimuli	2	5320
9.268	0.0	n/a	0	5561
10.955	0.0	feedback	4	6573
12.456	0.0	n/a	0	7474
```

This seems strange to me. Wouldn't a correct way to convert this be to collapse two rows associated with onset and offset of the event in the numpy array to a single row in the BIDS events file with a correct duration?

**Comment by sappelhoff** [comment]
Hi @hstojic thanks for your question.

MNE-BIDS currently **always** writes `0.0` as the duration of an event, as can be seen in the code for `_events_tsv` (see the code snippet below).

It would certainly be possible to calculate the exact duration from an events array such as the one that you have. I have two concerns:

1. Not every user would have the structure of two rows in the events array always belonging together. But that's more of a comment: We could check that and only write durations, if we have asserted the events structure that you have in your example
1. I have met many researchers (and including myself) who do **not** use their event markers this way. If I mark an event, I usually send a trigger (say `128`) and then leave it "ON" just barely enough so that it gets samples (say, for 1ms at 1000Hz sampling frequency of my recording device) then I reset the trigger value to `0`. This has nothing to do with how long the actual event was.

I think one could argue that your use of events values is good (and perhaps preferable to the one I outlined in point 2.) ... but it would be impossible to check. In my case, MNE-BIDS would then write faulty durations.

Perhaps @jasmainak has an opinion on this as well.

https://github.com/mne-tools/mne-bids/blob/22812d9c60ddecc9ed22d526b61fff9ec2ab43e8/mne_bids/write.py#L126-L182

**Comment by jasmainak** [comment]
@hstojic can you share what command you used to produce that events array? What were the arguments to `mne.find_events`? Perhaps we could triage based on what the array looks like, but I am not sure ...

**Comment by hstojic** [comment]
@jasmainak I collect events from a photodiode channel that I attach to the screen as I use browser based experiments and cannot send triggers to the scanner. I have written a small class for processing the photodiode signal and extract events from it, so not sure it would be useful. Otherwise, arrays always look like above, with slightly different events in different runs (tasks) - as far as I understand this is the usual format that MNE expects, no?

@sappelhoff I see your point, actually photodiode events were like that as well but then I computed end of events according to the real duration. I guess it doesnt hurt to have extraction of duration as default, if end of event lines are present. Then it will up to the creator of the data to specify what the duration really refers to - duration of the trigger or event itself.

I could easily not write the end of the event but that seems like a useful information that someone might use even if I dont end up using it.

**Comment by jasmainak** [comment]
It just seems a bit dangerous to me. Since the second column encodes not the duration but the previous value, it could mean different things in different contexts. Perhaps the `duration` in `raw.annotation` could be used if the all onsets match with the `events` ...

**Comment by hstojic** [comment]
perhaps a change in BIDS events specification, explicitly allowing for both trigger duration and event duration?

**Comment by sappelhoff** [comment]
> perhaps a change in BIDS events specification, explicitly allowing for both trigger duration and event duration?

This is technically already possible under the current BIDS specification, because we are allowed to specify an ["arbitrary amount of additional columns"](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/05-task-events.html)

literal quote:

> An arbitrary number of additional columns can be added. 

So what we **could** do, in MNE-BIDS is ...
1. always try to extract trigger durations
1. if we fail, nothing happens
1. if we succeed, we write an additional column in the events.tsv:, perhaps called `trig_duration`
  - and then we update `events.json` with a key `trig_duration` and the value describing what this column means

I would be fine with this. What do @jasmainak and @agramfort say? Would you be up to prepare the PR for this @hstojic ?

**Comment by agramfort** [comment]
+1 to add a duration columns in events.tsv in write_raw_bids in case not
all durations are zero

**Comment by jasmainak** [comment]
why not just write the `raw.annotations` if `events` is `None`? It already has duration in it. It's also closer to the `raw` data.

**Comment by agramfort** [comment]
Sounds good

**Comment by jasmainak** [comment]
@sappelhoff are you on it?

**Comment by hstojic** [comment]
Right, I missed the bit that we can add new columns to events file - adding `trig_duration` sounds like a good plan. 

@sappelhoff I could take it on me, but probably it will take a bit of time.

**Comment by sappelhoff** [comment]
Sounds great @hstojic :-) 

Looking forward to your PR!

**Comment by hoechenberger** [comment]
This can now be achieved by using annotations.
