### ISSUE TITLE
read_raw_bids specifically _parse_bids_filename fails when _ in bids directory

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-bids#230]
I would suggest passing only session level filepath to _parse_bids_filename because if you name the bids directory something like "data_BIDS" the underscore causes a parser error. 

Something like: "params = _parse_bids_filename(*op.join(bids_basename.split('/')[1:]), verbose) "on line 203 of read.py would work.

**Comment by jasmainak** [comment]
hmm ... indeed, can you propose a PR to fix this? You'll need to add a test which shows that it fails on `master` but passes on your branch

**Comment by alexrockhill** [comment]
Ok, will do.

**Comment by sappelhoff** [comment]
> read_raw_bids specifically _parse_bids_filename fails when _ in bids directory

perhaps this is because you are passing a `path` instead of the `filename`?

```Python
Parameters
----------
bids_fname : str
    Full name of the data file

```

We have had this discussion a few days ago ... and it should not make a difference whether a user passes a "path" or the actual filename ... we should always run `bids_fname` through `os.path.basename` as you suggest in your PR https://github.com/mne-tools/mne-bids/pull/231/files
