### ISSUE TITLE
pb writing empty room in subject folder

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-bids#287]
with @SophieHerbst we are trying to have the empty room for each of our subjects saved in the session folder as we have one empty room per subject but we hit a wall.

Run:
```
import os.path as op

import mne
from mne.datasets import sample

from mne_bids import write_raw_bids, make_bids_basename

data_path = sample.data_path()
output_path = op.join(data_path, '..', 'MNE-sample-data-bids')

er_raw_fname = op.join(data_path, 'MEG', 'sample', 'ernoise_raw.fif')
er_raw = mne.io.read_raw_fif(er_raw_fname)
bids_basename = make_bids_basename(subject='01',
                                   task='noise', run='01')
write_raw_bids(er_raw, bids_basename, output_path, overwrite=True)
```

it's not considered as emptyroom by write_raw_bids and as there is no dig
point it crashes. Thoughts?

**Comment by jasmainak** [comment]
hmm agreed, this should not crash.

**Comment by agramfort** [comment]
What’s the right fix?

**Comment by jasmainak** [comment]
This seems more like a documentation issue than a bug. Try this:

```py
import os.path as op

import mne
from mne.datasets import sample

from mne_bids import write_raw_bids, make_bids_basename

data_path = sample.data_path()
output_path = op.join(data_path, '..', 'MNE-sample-data-bids')

er_raw_fname = op.join(data_path, 'MEG', 'sample', 'ernoise_raw.fif')
er_raw = mne.io.read_raw_fif(er_raw_fname)
bids_basename = make_bids_basename(subject='emptyroom',
                                   task='noise', run='01', session='20021206')
write_raw_bids(er_raw, bids_basename, output_path, overwrite=True)
```

You need to save it in a subject called "emptyroom" and the session should be the date that matches your subject's recording. See also: https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html#empty-room-meg-recordings

**Comment by agramfort** [comment]
I understand the intention but I see pbs coming. 

If you anonymize we need to be careful with daysback

Also we need an easy way to retrieve the empty room data for a subject as currently you need to cook up something non trivial for new users 

Thoughts?

**Comment by SophieHerbst** [comment]
I second Alex, setting subject = 'emptyroom' and task = 'noise' lets me write the emptyrooms, but I would like them to be accessible by the subject's name, as the other files, especially since we want to anonymize these data. Would it be an option to reduce the if statement in line 1056 in write.py to
>  if  task == 'noise':

**Comment by jasmainak** [comment]
Hmm ... I think the specification mandates that we store it in a subject called ‘emptyroom’. Don’t think we should change that without changing the specification. Also you want to retrieve based on date not subject because a single subject could have made multiple visits on different days.

Now for anonymization, it means users must always set `raw.info[‘meas_date’]` so that the `meas_date` matches the raw file. We could have a small function `get_empty_room(subject_id)` that returns the `raw` object corresponding to the subject if there is only one visit.

**Comment by SophieHerbst** [comment]
Hm, so if I understand you correctly, I should name each subject's files with task and session (i.e. date if not anonymized), and have another subject called emptyroom with task='noise' and several sessions that each match one subject's? 

I might have missunderstood, but when I tried to name each subject's file by the specific session (recording date), I ran into trouble with the mne study template, where all subjects are expected to have the same sessions: `sessions = get_entity_vals(bids_root, entity_key='ses')`, which I assumed to be a general principle.

**Comment by agramfort** [comment]
if we don't amend the standard with need the get_empty_room function.

>
note that at Neurospin you have an empty per subject and not per day. So
you will
need to find the empty that is just before the first run of the subject.

@jasmainak wdyt? can you someone take a stab at it?

**Comment by jasmainak** [comment]
@SophieHerbst yes you should name each subject's file with task and session (may or may not be date), and have another subject called emptyroom with task='noise' and sessions corresponding to different dates. Then we can simply use the `scans.tsv` to match the two files or from `raw.info['meas_date']`. I can make a PR for this.

Regarding your second question, you're indeed right that subjects can have different sessions and this is not very well-exposed in MNE-BIDS. The reason is that it was not clear to us what would be the canonical way to query a BIDS dataset. Do you want an object that gives you the entire structure and allows iterations (e.g., BIDSHandler) or do you want to query with some filters -- give me filenames of subject A with session YY (e.g., Pybids style). What we came up with was sufficient for the datasets we observed so far but I am open to improving this. This should perhaps be discussed in a separate issue though.

**Comment by jasmainak** [comment]
By the way, empty room writing is documented here: https://mne.tools/mne-bids/auto_examples/convert_mne_sample.html#sphx-glr-auto-examples-convert-mne-sample-py. Maybe we should make a dedicated example to deal with empty room? Reading + writing

**Comment by agramfort** [comment]
+1 for an yes example

>

**Comment by SophieHerbst** [comment]
@jasmainak re: your comment about non-matching sessions for different subjects
this seems incompatible with mne-study-template in my hands:

I converted the sample data to BIDS, using this [example](https://mne.tools/mne-bids/auto_examples/convert_mne_sample.html#sphx-glr-auto-examples-convert-mne-sample-py), to run mne-study-template, which crashes because 
`sessions = get_entity_vals(bids_root, entity_key='ses')`
returns  `['01', '20021206']`, the latter of which only exists for emptyroom. 

>   File "/Users/sophie/repos/mne-study-template/01-import_and_filter.py", line 77, in run_filter
>     '"{}"'.format(search_str))
> 
> ValueError: Could not find input data file matching: "/Users/sophie/mne_data/MNE-sample-data-bids/sub-01/ses-20021206/meg/sub-01_ses-20021206_task-audiovisual_run-01_meg*"

**Comment by jasmainak** [comment]
@SophieHerbst I agree, this should be improved. Should we open a new issue to discuss this as it seems a general problem that's going to occur even if we don't have empty room?

**Comment by jasmainak** [comment]
Note we have an open PR on study template: https://github.com/mne-tools/mne-study-template/pull/41/files where the last commit essentially exposes this problem for runs (instead of sessions)

**Comment by SophieHerbst** [comment]
nice. this works on the basis of the events? 
But it seems that fixing the sessions / emptyroom will require a separate PR?

**Comment by jasmainak** [comment]
yep that would be a separate discussion. I think the easiest solution for now is to exclude the `'emptyroom'` subject when searching for sessions.
