### ISSUE TITLE
Project Comments (JOSS Review)

### ISSUE THREAD

**Issue by TomDonoghue** [mne-tools/mne-bids#305]
I have been looking through the code and project, due to reviewing the project for JOSS (openjournals/joss-reviews#1896). 

Here I am collecting a couple open thoughts / questions about the project:
- [x] Is there a minimum version of Python3 required? I guess that there is some minimum required sub-version of Py3 required, but it's not clear what that would be, and it might be useful to note that. 
- [x] Is it not standard to list out the required dependencies in a `requirements.txt` file? It could be this is no longer considered standard practice, but it struck me as odd that this isn't included. 
- [x] On the website, the text overlaps for inputs and docstrings. Not sure if there is a sphinx setting to fix this.
- [x] In the `Contributing.md` file, it is noted that the BIDS validator is required to run tests locally. I think it's worth specifying that this requires the CommandLine app (and not, for example, the Python library). It took me a while to get tests running, partly because I had to chase out how to get BIDSValidator set up as needed. 
- [x] Related to tests and dependencies, the current dev version fails a series of tests due to missing `pybv` if it's not installed, but this isn't listed as a requirement in the repo info nor in the Contributing file.
- [x] Note: Once I solved BIDSValidator and pybv, I did get the tests running locally, though one still fails - the `test_ctf` check fails on the last error check, for the "All measreument dates are None" part. I'm not sure why - I didn't dig into this. 
- [x] It might be worth adding a section to the README which links to the Contributing file, because otherwise this is not linked from the website, nor easily accessed from the README, and not totally obvious to find.
- [x] Perhaps my most general comment, is that if one starts at the examples, I'm not sure it's particularly clear where to start. I wonder if it might be useful for the new user if the examples were clustered into sections, for example into 'Intro', 'EEG', 'MEG' or something. And/or, perhaps, they could be ordered, with the most introductory example positioned first.
- [x] Relatedly, I wonder if it would be a useful extra example / starting point would be a file that explains the BIDS logic, in the context of electrophysiological data. The README links to the general BIDS site, but the general spec is more about MRI, and if one didn't already know, I don't think there's a clear path offered to motivate what BIDS means / looks like for EEG/MEG/iEEG. And 'Intro' example could briefly introduce some ideas, link to the separate specs more explicitly, and note things like supported file formats, etc.
    - [x] Or, another way to put it: the current site presumes one already know about MNE & BIDS and already knows why they want to use them together. In so far as it's considered within scope to motivate and promote why one should use BIDS, and what it looks like (within code / practical examples) I think a little more could be added (though this could reasonable be considered out of scope).

**Comment by sappelhoff** [comment]
Thanks for your review @TomDonoghue! I edited your post to turn the bullet points into check marks, so that we can mark more easily which points of yours we have already addressed. I hope that was OK with you :-)

Now, to get started:

> Is there a minimum version of Python3 required? I guess that there is some minimum required sub-version of Py3 required, but it's not clear what that would be, and it might be useful to note that.

Yes, minimum 3.5, same as for MNE-Python. Thanks for marking this, I have updated it in https://github.com/mne-tools/mne-bids/pull/306/commits/aff8fdc99da075522e23d9911a5e4786d9cd8af6

> Is it not standard to list out the required dependencies in a requirements.txt file? It could be this is no longer considered standard practice, but it struck me as odd that this isn't included.

In our installation we recommend that users work with [Anaconda](https://www.anaconda.com/), which usually works in "environments", so we provide a [`environment.yml`](https://github.com/mne-tools/mne-bids/blob/5809a8204f0fc9f18e772807312ecfd656a6d6d9/environment.yml#L1) file, which we also use in our CIs (see e.g., [here](https://github.com/mne-tools/mne-bids/blob/5809a8204f0fc9f18e772807312ecfd656a6d6d9/.travis.yml#L58)). Note however, that we try to keep installation very basic and assume that users do so by following how it's specified in the [README](https://github.com/mne-tools/mne-bids/blob/master/README.rst) ... I don't think a `requirements.txt` file would significantly simplify the installation at this point.

**Comment by sappelhoff** [comment]
> In the Contributing.md file, it is noted that the BIDS validator is required to run tests locally. I think it's worth specifying that this requires the CommandLine app

I absolutely agree - thanks! See the fix here: https://github.com/mne-tools/mne-bids/pull/306/commits/2cf52b85b91771630044823b0e0b4d9e75547813

> It might be worth adding a section to the README which links to the Contributing file, because otherwise this is not linked from the website, nor easily accessed from the README, and not totally obvious to find.

That's a fair point. I guess it's a bit of a hidden knowledge (or not enforced standard) that [the contributing guide in GitHub is always to be found in CONTRIBUTING.md](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors#adding-a-contributing-file)...  I have addressed your point by adding a section to our README here: https://github.com/mne-tools/mne-bids/pull/306/commits/4d3dbd81a6b0fe8c0a1a3b296fac6fc0c60effdc

Better be safe than losing a potential contributor :-)

**Comment by sappelhoff** [comment]
>  On the website, the text overlaps for inputs and docstrings. Not sure if there is a sphinx setting to fix this.

I tried to find what you mean by this @TomDonoghue but I didn't see it in either stable or latest docs ... could you please send a screenshot and a link to the page where you notice the issue?

> Related to tests and dependencies, the current dev version fails a series of tests due to missing pybv if it's not installed, but this isn't listed as a requirement in the repo info nor in the Contributing file.

Good catch, thanks. I actually went ahead and added *all* optional packages to the "to be installed" list for contributors: https://github.com/mne-tools/mne-bids/pull/306/commits/63aa343ed006730317cde897bf15c1f4d697239f ... note that normal users (as opposed to contributors) are not expected to run tests, so I only added this to the CONTRIBUTORS guide.

> Relatedly, I wonder if it would be a useful extra example / starting point would be a file that explains the BIDS logic, in the context of electrophysiological data. ...

I agree that users of `mne-bids` need a lot of knowledge about BIDS (and MNE-Python) already, but I do think that it's out of the scope of our package to provide a large introduction. Better places for this are the [bids starter kit](https://github.com/bids-standard/bids-starter-kit), however I am interested to hear @jasmainak's opinion on this. 

To think practical, I can imagine that we add a sentence or two to our README to better point users towards the MEEG aspect of BIDS (instead of only to BIDS in very general terms)

**Comment by TomDonoghue** [comment]
For the docs overlap page: sorry, I wasn't super specific, I meant an issue on the rendering of the API page. However, with a little more checking, I realized I had opened it up on (an old version of?) Safari, in which I see things like this:
<img width="781" alt="Screen Shot 2019-12-03 at 11 32 57 AM" src="https://user-images.githubusercontent.com/7727566/70083132-b3a41300-15c0-11ea-8dda-c981af513fd8.png">
But that this doesn't happen on Firefox or Chrome. I think this is more about one weird browser issue, and not something with your settings - sorry for not looking into that more!

For the last point, I do totally agree that really diving into explaining BIDS is out of scope, but I think what I was trying to get at is that it doesn't feel like there is a super clear path offered for a novice user who, say, sees this repo on `mne-tools` and wants to learn about BIDS, in the context of M/EEG. I think, like you suggest, even a quick statement like "If you are interested in learning more about BIDS the main page is here, a starter kit is here, and the specifications for MEG, EEG, iEEG are here, here, and here" in the README might help. In the context of a possible example, I was thinking something that does presume one has read, the EEG BIDS paper or spec, for example, but does a little more demonstration like "here is an example BIDS file structure", "here is an example BIDS metadata file", "here is a list of supported file formats", "here is a list of identifiers that can go in file names", etc. But again - up to y'all how you want to organize these kinds of things across the BIDS ecosystem. 

All the other noted points & fixes make sense and look good to me!

**Comment by jasmainak** [comment]
Sorry I am slow to catch up. Thanks @TomDonoghue for all the excellent suggestions for improvements.

I am fine adding some description of what BIDS is -- a standard for organizing data. So someone who knows MNE but not BIDS can become curious.

Also @sappelhoff , perhaps we could [order our examples](https://sphinx-gallery.github.io/stable/configuration.html#sorting-gallery-subsections) so that they follow some logical sequence going from easy introduction to what the file structure looks like, to reading, conversion, anonymizing etc?

**Comment by sappelhoff** [comment]
For the sake of completion:

> Note: Once I solved BIDSValidator and pybv, I did get the tests running locally, though one still fails - the test_ctf check fails on the last error check, for the "All measreument dates are None" part. I'm not sure why - I didn't dig into this.

@jasmainak fixed this in #307 

Next up: 

1. adding some meat to the description on BIDS
2. re-organizing examples

**Comment by sappelhoff** [comment]
Done:

1. add BIDS description: https://github.com/mne-tools/mne-bids/pull/312/commits/5f9a908ffa6827bcc62e5c61273e49821123b3b6

2. re-organized examples: https://github.com/mne-tools/mne-bids/pull/312/commits/3f17375427598c8a19870f2122e465ce40bf6629 ... loosely ordered from basic to advanced.

**Comment by sappelhoff** [comment]
all points have been addressed now :-) closing.
