### ISSUE TITLE
Update `meas_date` type check in `_scans.tsv` for MNE-Python v0.20

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#343]
#### Describe the bug
In version 0.20, MNE-Python raw.info['meas_date'] is now stored as a datetime object.

https://mne.tools/dev/generated/mne.Info.html#mne.Info

#### Additional information
1. Change the check in https://github.com/mne-tools/mne-bids/blob/4d0f463127e094156604864bd5a58a5dfc2ba917/mne_bids/write.py#L334-L337
to datetime? or use a try/except statement?

2. Perhaps a unit test to capture any changes in the upstream MNE-Python dependencies?

**Comment by adam2392** [comment]
I can fix this if given some thoughts on how the 1) type-checking should change, and 2) if just manually setting `raw.info['meas_date']` is enough in a unit test? 

Or would a specific dataset be useful.

**Comment by sappelhoff** [comment]
good catch, thanks @adam2392.

a PR is very welcome if it preserves behavior for MNE <0.20 and enables smooth running with also MNE = 0.20 (=current dev version). Regarding the practical implementation you could just see what makes sense (few lines, good readability, robustness are best).

re: test --> is there a test you could just extend? Otherwise yes, I think manually setting raw.info after reading would be fine for such a test!
