### ISSUE TITLE
File type suffixes 

### ISSUE THREAD

**Issue by kambysese** [mne-tools/mne-bids#4]
What's the consensus on handling suffixes like `-cov`, `-epo`, or `ave` in the BIDS file naming scheme? looks like we'd have to use the `_proc` label e.g., _proc-cov_meg.fif

**Comment by jasmainak** [comment]
If I remember correctly, these files are not meant to be stored in BIDS compatible folders. BIDS is meant only for raw files and the _proc is only for SSS or TSSS

**Comment by kambysese** [comment]
Ok I was thinking about derivative files referred to in the BIDS 1.0 docu. So it's safe to assume that the MEG derivative files would get their suffixes tacked onto their BIDS name e.g., sub-control01_ses-001_task-rest_run-01_proc-tsss_meg-epo.fif?

**Comment by jasmainak** [comment]
I don't think derivatives are really handled explicitly at the moment in BIDS-MEG. I am assuming it will be handled in a new specification. @teonbrooks what's your take on this?

**Comment by teonbrooks** [comment]
sorry for the delay, been on vacay. @jasmainak is correct, the spec is currently for the raw. @kambysese yes, that is also correct, but the derivative in this file pertains to mri data, not meg. we haven't begun a discussion on the derivative files. this is an important convo that we should have because a lot of shared data may lie at the epochs level, not the raw...

**Comment by jasmainak** [comment]
okay closing issue. Thanks @teonbrooks
