### ISSUE TITLE
citation policy?

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-bids#460]
In the last weeks we have found several papers/preprints/datasets that use MNE-BIDS but unfortunately do not cite it.

I think I might have found one more: https://openneuro.org/datasets/ds002778/versions/1.0.1. cc @alexrockhill ? ;-) 

**This is not due to ill-intention on part of the dataset curator** but simply lack of awareness and a clear policy on our end. Do we require datasets curated using MNE-BIDS to ask publications using the dataset to cite us? Or is it enough for the dataset to cite us and not require publications using the dataset to cite? I'm not exactly sure what's the right thing to do but we do need incentives to continue maintaining the software and citations is once of them.

cc @agramfort @adam2392 

EDIT: we could change `write_raw_bids` to include the reference. It might be on the verge of overkill but I want to hear opinions :)

**Comment by alexrockhill** [comment]
I changed the referenced dataset that I uploaded, thanks @jasmainak for catching that! As I said offline, it isn't the first thing that comes to mind to cite papers when uploading a dataset, you're more focused on the papers that used that data being cited so I would +1 for the `write_raw_bids` change.

**Comment by sappelhoff** [comment]
> In the last weeks we have found several papers/preprints/datasets that use MNE-BIDS but unfortunately do not cite it.

indeed. I contacted two authors and it turned out they really just forgot. I.e., lack of awareness / clear policy on our end.

# My opinion

I think people who use MNE-BIDS in any way should cite it. E.g., if they

- use it for full BIDS organization
- just for renaming BrainVision files
- ... just for anonymization
- ... etc. --> *any* use case

However, I **don't** think a citation is "required" if then a third party uses the product of an mne-bids user. E.g.,

- Alex formats a BIDS dataset and writes a dataset descriptor ... he cites MNE-BIDS (yay :tada: )
- Some random dude uses Alex's data and writes a paper, doing all analyses in Matlab ... he doesn't cite MNE-BIDS (I think that's fine)

# Enforcing

Now that's the difficult part. Making our functions "print reminders" upon usage can quickly become very annoying. I still have nightmares from firing up `psychopy`, which loads `pygame`, and then prints an annoying `Hello from the pygame community`. But maybe other people are not annoyed by this.

What I could imagine is that when we write a `dataset_description` or `README`, we automatically put a citation for MNE-BIDS in there.

**Comment by jasmainak** [comment]
>  I don't think a citation is "required" if then a third party uses the product of an mne-bids user.

The problem is that many folks use `mne-bids` _after_ they publish their paper. So they cannot cite us any more.

**Comment by agramfort** [comment]
it's a hard problem. I see often paper doing full studies with MNE and who
do not cite the papers.
I think we should educate and send friendly emails to fix this.
I would not print stuff in the terminal for this.

>

**Comment by adam2392** [comment]
**Newbie Thoughts**
I'm a bit newcomer to the repo, but I don't see the problem w/ adding the fix into `write_raw_bids`, since make_dataset_description happens there. I think the idea of mne-bids is way more then just formatting datasets. I've found it to be incredibly useful to "bottleneck" datasets into a fixed format, and then my IO becomes 10x shorter (and for that matter less error-prone). I think people should therefore still cite the repo even if they don't use the "write" abilities, since the "read" abilities are just as nice for (M/I)EEG. Idk how to best enforce that though besides doing what @agramfort suggested.

**What to Cite (Papers + Github Zenodo(?))**
A misc thought... but is there a Doi/Zenodo for the github itself? I'm not on the paper(s), but selfishly would obviously like to also cite the github repo in addition the publications, where there's some evidence of after-publication people (e.g. me :p) contributing.

**Comment by sappelhoff** [comment]
> A misc thought... but is there a Doi/Zenodo for the github itself?

there is (see https://doi.org/10.5281/zenodo.3580272), but these citations are not indexed on Google Scholar unfortunately, so the benefit is limited :-/

I would recommend to always cite the paper (which IS indexed) ... and optionally (if somebody wants to) cite the zenodo with the specific version of MNE-BIDS that was used --> but "on top" of citing the paper.

>  I'm not on the paper(s), but selfishly would obviously like to also cite the github repo in addition the publications, where there's some evidence of after-publication people (e.g. me :p) contributing

you are an author on the poster at least :-) (https://zenodo.org/record/3891836)

But I see what you mean. PR welcome for you to add yourself to https://github.com/mne-tools/mne-bids/blob/master/.zenodo.json --> in terms of author order I don't know, but perhaps on line 75 in the file would be good.

**Comment by jasmainak** [comment]
How about adding MNE-BIDS as an author in the README / dataset description? It's subtle but reminds people to acknowledge MNE-BIDS. And democratic too, since it does not list particular authors of MNE-BIDS. This way we can also trace datasets that were created with MNE-BIDS.

**Comment by sappelhoff** [comment]
> How about adding MNE-BIDS as an author in the README / dataset description? 

I'd prefer to insert a paragraph about citing MNE-BIDS into the README.

MNE-BIDS as an author probably has a higher chance to get overwritten without replacement.

**Comment by alexrockhill** [comment]
> MNE-BIDS as an author probably has a higher chance to get overwritten without replacement.

+1 I think I've done this actually, sorry all!

**Comment by jasmainak** [comment]
I think @alexrockhill volunteered to do this ;-) Waiting for the PR!

**Comment by sappelhoff** [comment]
thanks for https://github.com/mne-tools/mne-bids/pull/463 @alexrockhill, I love the PR title 😆 

another idea: perhaps we should add a citation reminder to our examples?

Or if adding an RST reminder to each example is too annoying, ... then perhaps we can at least `print(README)` of the README from @alexrockhill's https://github.com/mne-tools/mne-bids/pull/463 ... which would be a subtle reminder and a show of the functionality that MNE-BIDS references are automatically inserted?

(we don't have to `print(README)` in each example, ... but there are some, where it could fit)

**Comment by sappelhoff** [comment]
and one more idea that may be effective but not annoying:

Currently we write into `dataset_description.json`:

```JSON
{
    "Name": " ",
    "BIDSVersion": "1.2.2",
    "Authors": [
        "MNE-BIDS"
    ]
}
```

Perhaps we can change the author `MNE-BIDS` to `Please-Cite-MNE-BIDS-In-Your-Dataset-And-Paper`

Let me know what you think :)

**Comment by jasmainak** [comment]
yeah, good idea! Or: "MNE-BIDS (Please cite before removing this)"

**Comment by robertoostenveld** [comment]
Adding a software package (or its maintainers) as Author is IMHO not a good idea. It is not in line with the definition of authorship in most publication systems that I know, e.g. [SfN](https://www.jneurosci.org/content/20/1/F5) guidelines state that authorship should be based on a substantial intellectual contribution. See also [Elsevier](https://www.elsevier.com/authors/journal-authors/policies-and-ethics/credit-author-statement). Data publication is of course not so established yet, but [DataCite](https://schema.datacite.org/meta/kernel-4.3/doc/DataCite-MetadataKernel_v4.3.pdf) defines different roles (similar to CRediT).

Personally I would not want to be listed as author in a publication that used FieldTrip for data processing, without me being aware of its content, having (at least) conceptually contributed and being able to back/explain/defend the content of the publication. 

I think it would be more appropriate to automatically add MNE-BIDS to the `Acknowledgements`" field, see [here](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html). Another option that very recently was discussed (with the merge of the common derivatives) is to also use the `GeneratedBy` field for raw BIDS datasets.

**Comment by robertoostenveld** [comment]
By the way, I recommend that you register MNE-BIDS (and MNE-Python) on https://scicrunch.org/browse/resourcedashboard. MNE (the original, C/C++) is already registered there under https://scicrunch.org/scicrunch/Resources/record/nlx_144509-1/089bbd57-143b-54c3-852d-a722342e8d10/search?q=mne&l=mne.

**Comment by agramfort** [comment]
cool

I just added a request for an MNE-Python entry.

I'll let Mainak or Stefan do the same for MNE-BIDS

**Comment by sappelhoff** [comment]
> Adding a software package (or its maintainers) as Author is IMHO not a good idea.

At least in my mind, the dataset curator is entering their own name into the `authors` field, removing the `MNE-BIDS` entry. 

Having `MNE-BIDS (Please cite before removing this)` in the `authors` field should serve merely as a reminder to cite MNE-BIDS.

> think it would be more appropriate to automatically add MNE-BIDS to the Acknowledgements" field

I would be open to let MNE-BIDS write an empty `authors` field and instead add "itself" to the `acknowledgements` field.

But then users may think that that's already enough of a "citation" ... whereas we actually want them to cite BIDS and MNE-BIDS in their manuscript, so that

1. we have some incentive to continue our work and so that 
1. readers and users of the paper/dataset are becoming aware of BIDS and MNE-BIDS.

>  also use the GeneratedBy field for raw BIDS datasets

yes, I think that'd be nice, but I think `GeneratedBy` currently works only for derivative datasets :thinking: [see spec](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#derived-dataset-and-pipeline-description)

> I'll let Mainak or Stefan do the same for MNE-BIDS

I am on it :+1:

**Comment by alexrockhill** [comment]
I agree with @robertoostenveld about the author's point, maybe instead of `MNE-BIDS (Please cite before removing this)` it should just be `For publications, please add the MNE-BIDS citations in the README to your manuscript for before removing this` to be completely unambiguous that the citation is to be in the paper and not just on OpenNeuro/OSF.

**Comment by ezemikulan** [comment]
Hi, in my case, when I originally submitted the article, the MNE-BIDS paper was not out yet, then I could have added the citation during the last revision stage but it slipped under the radar (6 months later). I'm pretty sure that a terminal output wouldn't have helped but maybe having to overwrite a field on the README might have worked (even though the last review was about 7 months after exporting the data and I would have probably missed the chance all the same).

In any case, I believe that adding the "For publication, please add..." legend , as @alexrockhill suggested, on the README might be the most effective reminder, probably under the Acknowledgments section as it is a bit less "invasive" than if it were in the Authors field and it serves the purpose in the same way.

**Comment by alexrockhill** [comment]
@ezemikulan I think the dual purpose for having it in the authors field is so that the authors field is not empty and thus the dataset passes the BIDS validator (which is also important for tests). Thus something else would have to go in the authors. IMO putting it there with a clear "delete me" might be the most efficient rather than blank/temp authors passing the validator  causing people to have blank/temp authors in their published dataset. The way it is could still lead to some embarrassing "Please delete this" as authors of a published dataset but that would have to be US Congress + ALIK levels of not paying attention.

**Comment by sappelhoff** [comment]
Apparently GitHub has a new feature to advertise the adequate software citation from the main repo page: https://twitter.com/natfriedman/status/1420122675813441540

you can check out an example here: https://github.com/jorvlan/open-visualizations

Not sure yet whether this is intended for repos that do not yet have a canonical citation (like we do, JOSS) ... or whether we could just put our JOSS citation into a `CITATION.cff` file, and push it. In any case: It's interesting and nice, I think :)

![image](https://user-images.githubusercontent.com/9084751/127298619-46fd877f-62a5-4b2c-989b-4acbcc471ee5.png)

**Comment by hoechenberger** [comment]
Yes but as far as I understand, you cannot ask it to put our journal publication there. If that's true, then it's pretty much useless for now...

**Comment by agramfort** [comment]
why can't you put the citation to JOSS paper on mne-bids?

**Comment by sappelhoff** [comment]
Something like this would be possible:

```

# YAML 1.2
# Metadata for citation of this software according to the CFF format (https://citation-file-format.github.io/)
cff-version: 1.1.0
message: If you use this software, please cite it using these metadata.
title: 'ANNIS'
doi: 10.5281/zenodo.2563138
authors:
- given-names: Dummy
  family-names: User
  affiliation: Humboldt-Universität zu Berlin
  orcid: https://orcid.org/0000-1234-5678-9101
version: annis-3.6.0
date-released: 2019-02-12
repository-code: https://github.com/korpling/ANNIS
license:  Apache-2.0
references:
  - type: article
    title: "ANNIS3: A new architecture for generic corpus query and visualization"
    year: 2016
    doi: 10.1093/llc/fqu057
    authors:
      - family-names: Dummy
        given-names: User
        orcid: https://orcid.org/0000-1234-5678-9101
        affiliation: Humboldt-Universität zu Berlin
      - family-names: Other
        given-names: User
        affiliation: Georgetown University
    journal: Digital Scholarship in the Humanities
    volume: 31
    issue: "1"
```

see: https://github.com/citation-file-format/citation-file-format/blob/9879c64a37a9d4f3f18b67594aa3f3bf763fb69a/test/1.1.0/doi-with-slash/CITATION.cff#L1-L32

**Comment by sappelhoff** [comment]
after #1028 is done I'll migrate the `.zenodo.json` file to a `CITATION.cff` file and close this issue. CITATION.cff supports all that we need and discussed above.

I also unpinned this issue because we have a steady stream of citations coming in for our software now :-)
