### ISSUE TITLE
BIDSPath.entities

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#519]
Hello, I just worked with the latest `BIDSPath` (amazing work, @adam2392!) and came across something we should rethink.

Currently, `BIDSPath` has an `entity` property:
https://github.com/mne-tools/mne-bids/blob/ff3e4a712e7f863997fa5f79ea43dc3508a7c831/mne_bids/path.py#L115-L128

There are two things problematic with how it's currently implemented:
- `suffix` is no entity, according to BIDS
- `modality` is missing

I quickly tried to fix this, but after a few minutes realized that it might not be so easy, given how some internals currently work.

But I also wondered why `BIDSPath.entities` should be public anyway. Users can conveniently retrieve entities, suffix etc via their respective `BIDSPath` attributes. So I don't see why we would need `.entities` too, esp. considering that it only encodes a part of what is required to construct a path. I can see why we would want to use this **internally**, but it probably shouldn't be part of the public API.

Thoughts?

**Comment by agramfort** [comment]
+1 **not** to store in entities what are not BIDS entities but rather as
attributes

>

**Comment by adam2392** [comment]
Easy fix! Fixed it in: #517 

where we migrate suffix out, and add modality in. 

https://bids-specification.readthedocs.io/en/stable/99-appendices/04-entity-table.html

According to the spec...now modality can be part of the filename as `mod-<modality>`? I was not aware of this, but it also doesn't seem to be used anywhere else in the spec. Regardless, I think it's safe to add to the `entities` property because it's specified in the BIDS entity table.

**Comment by hoechenberger** [comment]
It's actually a different use of the term / key "modality", see

https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#anatomy-imaging-data

That's really ... not so cool ☹️ The standard effectively says that for the **modality** `anat` you can have different **modalities** of data acquisition... Even more, in some cases it's just used as a suffix (`*_T1w`) in others it's used as a key-value pair of entities (`*_mod-T1w_`)
Oh my...

**Comment by agramfort** [comment]
it's seems the standard needs a PR...

>

**Comment by sappelhoff** [comment]
> it's seems the standard needs a PR...

:confused: indeed, clarifications are welcome.

**Comment by adam2392** [comment]
Wow that is... unfortunate lol. I think wrt `modality`, it can be safe to say since we don't work w/ anat a lot in this package, we reserve `modality` for the directory level name (i.e. 'ieeg', 'eeg', 'anat', 'meg', 'func', etc.) for now until a clear up in BIDS spec.

In #517 I took out `suffix` and also added in `modality`, so hopefully that's closer to what we want now.

**Comment by jasmainak** [comment]
please complain on bids-specification github :) we need representation for ephys

**Comment by adam2392** [comment]
> please complain on bids-specification github :) we need representation for ephys

Done.

**Comment by hoechenberger** [comment]
I guess this can be closed for now.
