### ISSUE TITLE
copyfile_eeglab not working

### ISSUE THREAD

**Issue by nrosjat** [mne-tools/mne-bids#652]
### Description

I am currently attempting to copy EEGLAB files via copyfiles_eeglab with a new (BIDS compliant) name. The files are moved and renamed according to the specifications. However, when trying to open those files with MNE there is an error message:

```
Traceback (most recent call last):

  File "<ipython-input-17-8c31a528db9f>", line 1, in <module>
    raw_bids = mne.io.read_raw_eeglab('sub-001_ses-D1_task-RS2_run-02_eeg.set')

  File "C:\Users\Nils Rosjat\Anaconda3\lib\site-packages\mne\io\eeglab\eeglab.py", line 222, in read_raw_eeglab
    eog=eog, verbose=verbose, uint16_codec=uint16_codec)

  File "<decorator-gen-216>", line 24, in __init__

  File "C:\Users\Nils Rosjat\Anaconda3\lib\site-packages\mne\io\eeglab\eeglab.py", line 326, in __init__
    info, eeg_montage, update_ch_names = _get_info(eeg, eog=eog)

  File "C:\Users\Nils Rosjat\Anaconda3\lib\site-packages\mne\io\eeglab\eeglab.py", line 145, in _get_info
    ch_names, eeg_montage = _get_eeg_montage_information(eeg, has_pos)

  File "C:\Users\Nils Rosjat\Anaconda3\lib\site-packages\mne\io\eeglab\eeglab.py", line 123, in _get_eeg_montage_information
    ch_pos=dict(zip(ch_names, np.array(pos))),

TypeError: unhashable type: 'numpy.ndarray'
```

When comparing the original MATLAB structure:
![before](https://user-images.githubusercontent.com/34684014/101466558-93c8cd00-3941-11eb-9a90-c29db305b6a5.png)

with the newly created structure:
![after](https://user-images.githubusercontent.com/34684014/101466607-a216e900-3941-11eb-9979-26624a9e0f4b.png)

I saw that several entries were replaced by numpy array objects. This seems to happen already in

https://github.com/mne-tools/mne-bids/blob/3d96c5b2af004b57085b5c9bf884e18279707a3c/mne_bids/copyfiles.py#L531-L532

When replacing loadmat with `read_mat` (from mne.externals.pymatreader) this seems to work better, but still after saving the dict with `savemat` the same issue remains.

### Script used for conversion

**mne_bids version: 0.5**

```python
import os.path as op
import os

import mne

from mne_bids import BIDSPath
from mne_bids.copyfiles import copyfile_eeglab

parent_dir = op.abspath('..')
data_path = op.join(parent_dir,'data')

sub_dirs = ['001']
sessions = ['D1']
tasks = ['Tap']

for sub_dir in sub_dirs:
    for session in sessions:
        for task in tasks:
                sub_path = op.join(data_path, sub_dir, 'ses-' + session)
                sub_id = os.listdir(sub_path)[0].split('_')[0]
                set_name = sub_id + '_' + session + '_' + task + '_Nils_IntRef_CSD.set'
                set_file = op.join(data_path, sub_dir, 'ses-' + session,set_name)
                set_rename = 'sub-' + sub_dir + '_ses-' + session + '_task-' + task + '_desc-CSD.set'
                set_file_renamed = op.join(data_path, 'sub-' + sub_dir, 'ses-' + session, 'eeg', set_rename)
                copyfile_eeglab(set_file, set_file_renamed)
```

**Comment by sappelhoff** [comment]
Thanks for the thorough report @nrosjat! What's surprising to me is, that in our test for the `copyfile_eeglab` function, this issue does not come up.

See: https://github.com/mne-tools/mne-bids/blob/3d96c5b2af004b57085b5c9bf884e18279707a3c/mne_bids/tests/test_copyfiles.py#L184-L205

and that's although in that test we also check a `.set` + `.fdt` combination of files :thinking:

**Comment by sappelhoff** [comment]
I also see that [`loadmat`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.loadmat.html) say that only: `v4 (Level 1.0), v6 and v7 to 7.2 matfiles are supported.`

So recent .mat files won't be supported by mne-bids :thinking: I don't know whether EEGLAB specified a specific MAT-file version when writing the .set and .fdt files.

Let's try our chance with @cbrnr: Do you have EEGLAB set+fdt experience and immediately see the issue here?

**Comment by nrosjat** [comment]
At least when reading in the original file with `read_mat` it seems to be a `MATLAB 5.0 MAT-file`.

**Comment by sappelhoff** [comment]
Mhh so it *could* be an issue of `loadmat`, which does not explicitly state that it supports v5 ... (it looks like only v4, v6, v7-v7.2 are supported).

BUT you say that the issue also occurs with `pymatreader`. Did you make code adjustments?

I feel like we should generally use [pymatreader](https://pymatreader.readthedocs.io/en/latest/) rather than scipy loadmat because (i) it's what MNE uses and ships, so we do not add a new dependency to mne-bids, and (ii) because of this statement:

> pymatreader is a small python package that provides a consistent way of loading **all** versions of Matlab .mat files.

(emphasis added by me)

**Comment by nrosjat** [comment]
I didn't make any adjustments to pymatreader and loading seems to work properly there. However, after saving with `savemat` and reloading the same way using `pymatreader`, I get the same issue as before.

**Comment by hoechenberger** [comment]
> I feel like we should generally use [pymatreader](https://pymatreader.readthedocs.io/en/latest/) rather than scipy loadmat 

+1 on this one

**Comment by hoechenberger** [comment]
@nrosjat If you could share one of the problematic files with me, I can certainly have a look! My email address is richard.hoechenberger@gmail.com

Best wishes!

**Comment by sappelhoff** [comment]
> However, after saving with savemat and reloading the same way using pymatreader, I get the same issue as before.

I see :thinking: 

Could you try to write the SET files as MAT v7.3, which is HDF5 --> if it can be done with the hdf5 version that MNE ships: https://github.com/mne-tools/mne-python/blob/master/mne/externals/h5io/_h5io.py

(... because we wouldn't want to add a dependency).

Then we can do:

- if everything is in the SET
    - read with pymatreader to check that EEG struct is present - if not: raise error
    - just copy the file without touching it
- if we have SET+FDT
    - read with pymatreader
    - save with the h5io that MNE ships (to MAT format v7.3 ... but with .set extension obviously)

**Comment by nrosjat** [comment]
> Could you try to write the SET files as MAT v7.3, which is HDF5 --> if it can be done with the hdf5 version that MNE ships: https://github.com/mne-tools/mne-python/blob/master/mne/externals/h5io/_h5io.py

I just tried, but got the following `TypeError`

```
Traceback (most recent call last):

  File "<ipython-input-11-e7c8076546c3>", line 1, in <module>
    write_hdf5('test_mat.set',test_mat,overwrite=True)

  File "C:\Users\Nils Rosjat\Anaconda3\envs\mne-bids\lib\site-packages\mne\externals\h5io\_h5io.py", line 113, in write_hdf5
    _triage_write(title, data, fid, comp_kw, str(type(data)),

  File "C:\Users\Nils Rosjat\Anaconda3\envs\mne-bids\lib\site-packages\mne\externals\h5io\_h5io.py", line 149, in _triage_write
    _triage_write(

  File "C:\Users\Nils Rosjat\Anaconda3\envs\mne-bids\lib\site-packages\mne\externals\h5io\_h5io.py", line 232, in _triage_write
    raise TypeError(err_str)

TypeError: unsupported type <class 'bytes'> (in <class 'dict'>["__header__"])
```

**Comment by sappelhoff** [comment]
Of course, the quickest route to solving this would be to re-save your files in EEGLAB using the "onefile" approach, so that you only have `.set` and not `.set`+`.fdt`. 

I cannot work on a fix for this issue right now, so either you try to fix it on your own (and let us know :slightly_smiling_face: ) or perhaps @hoechenberger can spend a cycle on this?

**Comment by nrosjat** [comment]
For now, we just renamed the files with EEGLAB itself.

I'll try to find a fix for the issue, but any input from @hoechenberger is very appreciated.

**Comment by cbrnr** [comment]
It's been too long since I've last used the EEGLAB format, but you already discovered that currently they default to v7.3 files.

I'd also switch to `pymatreader` instead of `scipy.io.loadmat`. However, I don't understand why you need to write to .mat files again?

**Comment by sappelhoff** [comment]
> I'd also switch to pymatreader instead of scipy.io.loadmat. However, I don't understand why you need to write to .mat files again?

the "copyfile" function is basically to rename existing files to BIDS convention. And for many file formats this turns out to be more complicated than renaming the files, because internal fields may have to be adjusted as well. As in BrainVision, EEGLAB, ...

@nrosjat did you share the problematic file with @hoechenberger it'd be invaluable to fix this issue.

**Comment by nrosjat** [comment]
> @nrosjat did you share the problematic file with @hoechenberger it'd be invaluable to fix this issue.

Yes, he should have received an email.

**Comment by hoechenberger** [comment]
I will have a look later tonight, currently busy with something else. But thanks for sending the file so quickly!

**Comment by hoechenberger** [comment]
> the "copyfile" function is basically to rename existing files to BIDS convention.

Well… only that nowhere does it enforce BIDS conformity. I'm honestly wondering if these functions currently do more harm than good…

**Comment by cbrnr** [comment]
Thanks @sappelhoff. I agree with @hoechenberger - EEGLAB is not part of the BIDS standard, so renaming some files and fields will still not produce a valid BIDS dataset. I think writing to .mat will be a challenge (or at least some work) because there is no readily available Python package for writing .mat files.

**Comment by hoechenberger** [comment]
My point was more that if anything, this copying functionality should be part of `write_raw_bids` so we would ensure that the produced file names are BIDS-compatible. I'm okay with copying over EEGLAB data even if it's not (yet?) part of the standard

**Comment by cbrnr** [comment]
OK, got it. We don't even need `pymatreader` if we only use it to load files < v7.3 (non-HDF5). `scipy.io.loadmat` now has a `simplify_cells` parameter which produces a nice dict from cell arrays.

**Comment by hoechenberger** [comment]
@nrosjat Ok starting to look into this now. Will report back once I have results.

On another side note, why are you using MNE-BIDS to process those EEGLAB data, anyway? Wouldn't it be more convenient for EEGLAB users to use something like this: https://github.com/sccn/bids-matlab-tools/wiki ?

**Comment by hoechenberger** [comment]
So the issue with @nrosjat's file is that we screw up the channel names during reading: they're read as lumpy arrays of individual characters and never concatenated to complete strings again. I have changed this behavior "globally" for `loadmat` by passing `chars_as_strings=True` (instead of `False`, which we used previously), and I can successfully read the file and all tests pass. Does anybody remember why we had `chars_as_strings=False` in the first place? If it's important, I will have to come up with a different solution (i.e., loop over channels and concat the characters to proper channel names one by one)

**Comment by sappelhoff** [comment]
ah nice, sounds simple enough! I don't remember why chars_as_strings was set to False.

**Comment by hoechenberger** [comment]
I've added some more info at the PR  #653

**Comment by nrosjat** [comment]
> On another side note, why are you using MNE-BIDS to process those EEGLAB data, anyway? Wouldn't it be more convenient for EEGLAB users to use something like this: https://github.com/sccn/bids-matlab-tools/wiki ?

Actually, I used that one before and I have no idea why my colleague insisted on using MNE-BIDS for EEGLAB data.

> this copying functionality should be part of write_raw_bids only, so we would ensure that the produced file names are BIDS-compatible

I was also planning to copy and rename some derivates with this function. This has the advantage that I can also add the `_desc-<label>` to the filename which is as far as I know not supported with `write_raw_bids`, right?
