### ISSUE TITLE
check argument works differently in BIDSPath.__init__() vs BIDSPath.update()

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#734]
@adam2392 it seems #729 missed something in `BIDSPath.update()`:

```python
from mne_bids import BIDSPath

# good
p = BIDSPath(suffix='dataset_description', extension='.json', check=False)

# error
p = BIDSPath(extension='.json')
p.update(suffix='dataset_description', check=False)
```

**Comment by sappelhoff** [comment]
the issue here is that for the error case you initialize the BIDSPath without `check`, so it's defaulting to TRUE

then in the update call, the check for false chars (what's triggering the error) is happening BEFORE updating `check` from True to False.

The fix is thus, to first update check during the update call.
