### ISSUE TITLE
Link checks sometimes take forever

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#780]
I noticed that sometimes the Circle build take forever to finish because the link checks are super slow because we constantly hit GitHub rate limits when checking the different issues references in the changelog. For example:

```
(whats_new_previous_releases: line  268) redirect  https://github.com/mne-tools/mne-bids/issues/582 - with Found to https://github.com/mne-tools/mne-bids/pull/582
-rate limited-   https://github.com/mne-tools/mne-bids/issues/611 | sleeping...
-rate limited-   https://github.com/mne-tools/mne-bids/issues/612 | sleeping...
(whats_new_previous_releases: line  152) redirect  https://github.com/mne-tools/mne-bids/issues/601 - with Found to https://github.com/mne-tools/mne-bids/pull/601
(whats_new_previous_releases: line  149) redirect  https://github.com/mne-tools/mne-bids/issues/603 - with Found to https://github.com/mne-tools/mne-bids/pull/603
-rate limited-   https://github.com/mne-tools/mne-bids/issues/631 | sleeping...
-rate limited-   https://github.com/mne-tools/mne-bids/issues/636 | sleeping...
(whats_new_previous_releases: line  150) redirect  https://github.com/mne-tools/mne-bids/issues/610 - with Found to https://github.com/mne-tools/mne-bids/pull/610
-rate limited-   https://github.com/mne-tools/mne-bids/issues/648 | sleeping...
(whats_new_previous_releases: line  175) redirect  https://github.com/mne-tools/mne-bids/issues/611 - with Found to https://github.com/mne-tools/mne-bids/pull/611
```
Can we maybe disable those checks for PRs and only run them on `main` or something? Or use a shorter timeout so we error out earlier instead of waiting so long for a retry?

**Comment by sappelhoff** [comment]
> Can we maybe disable those checks for PRs and only run them on main or something? Or use a shorter timeout so we error out earlier instead of waiting so long for a retry?

running only on `main` seems reasonable.

I looked for some solution like storing a GitHub API token in circleci user settings so that we wouldn't get the rate limitations, but my brief search (couple of weeks ago) didn't yield anything.

Do you know more perhaps @larsoner ?

**Comment by larsoner** [comment]
1. Checking links on every PR seems like overkill. In MNE we do it once a week [on a schedule](https://github.com/mne-tools/mne-python/blob/main/.circleci/config.yml#L522-L533) (Sunday when traffic is usually low anyway), and recently made it so that `[circle linkcheck]` would also run it. I would just adapt that.
2. Checking the GitHub links is largely unnecessary. We can trust the `:gh:` magic to work, GH isn't changing those URLs (and I always check by eye that the number is correct for a given PR anyway). So in MNE we also have in our Makefile:
    ```
    @$(SPHINXBUILD) -b linkcheck -D nitpicky=0 -D plot_gallery=0 -D 
    exclude_patterns="cited.rst,whats_new.rst,configure_git.rst" -d _build/doctrees . _build/linkcheck
    ```
    Notice the exclusion of whats_new.rst. It makes it so that the GitHub links are never checked. It's a bit sloppy perhaps but it 
    seems to work okay. Our linkcheck runs in about 5 minutes.

    In principle you could probably use a GH token but again it seems like overkill.
3. Also FWIW we have in our `conf.py`:
    ```
    linkcheck_anchors = False  # saves a bit of time
    linkcheck_timeout = 15  # some can be quite slow
    ```

Come to think of it, the exclusion in (2) also makes it so that people's personal links are never checked, but this could be worked around pretty easily by making a secret `:orphan:` page that just includes `names.inc`. I'll probably make a PR for that.
