### ISSUE TITLE
[BUG] overwrite param is overly aggressive

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#82]
When we want to iteratively create a BIDS directory, overwrite will behave unexpectedly.

Example:
- I have 2 runs of the same task (however, single session ... so `session_id=None`)
- I load the data for run 1 and call `raw_to_bids`
- Then I repeat the same process for run 2

... if in the example `overwrite=True`, then I will end up only having run 2, because run 1 gets deleted:

https://github.com/mne-tools/mne-bids/blob/e03f013cfc897d116ce4d67d7bce6204d94a40a7/mne_bids/mne_bids.py#L504-L514

The issue: `overwrite` should only overwrite existing files, but it potentially removes whole directories with their contents (`sh.rmtree`), thereby discarding innocent data ;-)

**Comment by jasmainak** [comment]
@sappelhoff I discussed quite a bit this param with @monkeyman192 in other issues and PR. I am thinking that we should redesign this parameter to be called `mode` and it should accept three (or maybe four) possible arguments: 'overwrite', 'clean_overwrite' (?), 'append' and 'error'. The default should be 'append' or 'overwrite'.

**Comment by jasmainak** [comment]
Note that `bids-validator` will actually throw an error if you have "innocent" files lying around in your BIDS folder :-)

**Comment by monkeyman192** [comment]
Yep, so my closed PR #43 attempted to address this, but too much changed so it wasn't worth trying to rebase it (and it didn't quite cover all the cases as mentioned by @jasmainak )
I think to solve this problem we need to consider the different files produced and how we want to handle them.

The files produced by mne-bids fall into two general categories:

1. Files that are unique to a specific set of acquisition parameters (eg. session, task, acq etc):
 - coordsystem.json
 - channels.tsv
 - meg.json
 - events.tsv
 - <manufacturers specific MEG/EEG data>
 - headshape.< extension>
2. Files that contain information about multiple acqusitions:
 - scans.tsv
 - participants.tsv

Each of these two categories we expect to be overridden in different ways.
Category 1 has 2 different options:
 - **override** file if new file has same name
 - raise **error** if file already exists

Category 2 also has two different options:
 - **override** file if it already exists (essentially **clear** the file and start again)
 - **append** to the file

(I don't think raising an error if the file exists makes sense as the file for multi-session data *should* exist)
I think it would be good to have the a default option which does the action you would generally want to happen. To this end I propose the following 3 *override* options:

1. "default" -  **override** category 1 | **append** category 2
2. "error" - **error** category 1 (maybe skip error check on headshape file) | **override** category 2 (could have the processing of these files at the end so overriding only happens if no errors occur)
3. "clear" - remove tree (as currently happens) then **override** category 1 | **override** category 2

**Comment by monkeyman192** [comment]
I'll give an example of what I imagine the docstring would look like to see if it would make sense:

```python
"""
    overwrite : str, one of ('default', 'error', 'clear')
        How any existing files should be handled when new data is produced.
        Defaults to 'default'.
        - 'default': Any file that doesn't contain a list of contents (such as
            the participants.tsv or scans.tsv file) will be overridden. List
            files will have the new data appended.
        - 'error': If a file already exists, raise an error (TBD).
        - 'clear': Completely clear the session level BIDS directory, removing
            any previously existing data and placing the new data in this
            folder.
"""
```
Also, +1 to removing the `sh.rmtree` function as it is 100% not what we want happening by default.

**Comment by jasmainak** [comment]
okay yeah, agreed. This looks better than the explanation in the comment before. Two comments however:

> List files will have the new data appended.

Is channels.tsv also a list file? Maybe we should just make an exception for these two files? Do you see more such files that might have these exception?

> 'default'

related to the above comment. "Default" doesn't speak to me. It doesn't say what you're going to do. Can we call it "overwrite"? Since we overwrite all files except those two ...

**Comment by monkeyman192** [comment]
> Is channels.tsv also a list file?

Oh, good point. I wasn't sure the best way to name them. Maybe just explicitly would be best.
eg.
```python
"""
        - 'default': Any file that already exists will be overridden with new data, except `participants.tsv` and `scans.tsv` which will have the new data appended intelligently.
"""
```
> Do you see more such files that might have these exception?

Not within the MEG specification that I can see. But probably within other specifications there may be (does the EEG spec have anything extra?)

>  "Default" doesn't speak to me

Yeah I understand, I just thought it just makes it more obvious which option you want. But I guess if we were having this option as the default one anyway, then it wouldn't matter as the user would have to go out of their way to change the option. (ie. `Defaults to 'overwrite'`)

**Comment by sappelhoff** [comment]
> Not within the MEG specification that I can see. But probably within other specifications there may be (does the EEG spec have anything extra?)

No, the only additional file is the `electrodes.tsv`, which will be written once per subject. :-)

> Also, after looking up the exceptions we could use, I suggest we raise a FileExistsError for 'error'.

+1

**Comment by monkeyman192** [comment]
> No, the only additional file is the electrodes.tsv, which will be written once per subject. :-)

Ok, that's easy then.
If no-one else wants to I'll write up a PR for this tomorrow

**Comment by jasmainak** [comment]
@monkeyman192 love your enthusiasm :) PR is welcome !
