### ISSUE TITLE
Are we able to support "writing to EDF"? If so, what will it take?

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-bids#840]
Hi,

Perhaps this is also an issue in mne-python. This question keeps coming up on in my lab and I'm wondering what it would take to support "writing to EDF"? 

Currently, there are https://gist.github.com/skjerns/bc660ef59dca0dbd53f00ed38c42f6be and [pyedflib](https://github.com/holgern/pyedflib), which has over 250k downloads. I have to imagine that there is some degree of robustness now in terms of "writing EDF files". I know that I've had some trouble myself 2-3 years ago when I was trying, so don't know if those issues are still issues.

What sort of tests would we want to see in order to support a `write_raw_bids(format='edf')` in mne-bids? Would we depend on pyedflib, or need to PR a writer into `mne-python`?

**Comment by agramfort** [comment]
I would follow the way it's done for brainvision.

>

**Comment by sappelhoff** [comment]
There is also https://github.com/bids-standard/pyedf, which is pure Python, not depending on EDFlib. Having that said: pyedf doesn't see a lot of activity ... whereas EDFlib is probably the gold standard for reading and writing EDF, so +1 for pyedflib, and depending on it (optionally, like we do for pybv)

**Comment by sappelhoff** [comment]
we **could** also improve the "export" functionality of MNE-Python https://mne.tools/dev/export.html?highlight=export#module-mne.export and then make use of that in MNE-BIDS. Not sure what is better.

**Comment by adam2392** [comment]
^ can we add then exporting for edf and bv? With the optional dependencies in mne-python? And then wrap that API here in mne-bids?

Back story: doing some ICA rejections in EEGLAB and then would like to read in the scalp EEG to Persyst. However Persyst only reads manufacturer formats or EDF.

**Comment by sappelhoff** [comment]
> can we add then exporting for edf and bv? With the optional dependencies in mne-python? And then wrap that API here in mne-bids?

I think the infrastructure for doing that is there in MNE-Python, ever since EEGLAB export was recently added in https://github.com/mne-tools/mne-python/pull/9192

So I think it's up to a brave person to make the PRs (and discuss it in an MNE-Python issue beforehand :-)

Once it's in MNE-Python, adopting in MNE-BIDS should become nicer, I think.

**Comment by Teuniz** [comment]
> There is also https://github.com/bids-standard/pyedf, which is pure Python, not depending on EDFlib. Having that said: pyedf doesn't see a lot of activity ... whereas EDFlib is probably the gold standard for reading and writing EDF, so +1 for pyedflib, and depending on it (optionally, like we do for pybv)

FYI there's also a pure Python implementation of EDFlib:  

https://www.teuniz.net/edflib_python/

This is a 1 to 1 translation from the original C-version to Python.
Holgern's PyEDFlib forked the C-version of EDFlib and made many modifications to it which I don't support.
I write this so that you all can make an informed decision.

**Comment by adam2392** [comment]
This was closed by me in #863
