### ISSUE TITLE
Saving Intracranial Coordinates in BIDS

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-bids#856]
How should intracranial electrodes in "head" coordinates be handled? Should there be a `trans` argument in `write_raw_bids`? That would get to surface RAS but that doesn't look like one of the options in the error. Maybe that option needs to be added, seems like a lot of options though so someone may have thought about this thoroughly. To me, it makes sense to save them in surface RAS with a T1 in the BIDS directory, that seems about as easy to understand and reproducible as it can be. That would involve adding a `trans` argument and making whatever is the coordinate frame for surface RAS an acceptable option if a `trans` is provided.

Minimally reproducible script

```
import os
import os.path as op

import mne
import mne_bids

misc_path = mne.datasets.misc.data_path()
raw = mne.io.read_raw(op.join(misc_path, 'seeg', 'sample_seeg_ieeg.fif'))
tmp_dir = mne.utils._TempDir()
path = mne_bids.BIDSPath(root=tmp_dir, subject='sample', task='Motor')
mne_bids.write_raw_bids(raw, path)
```

Stack trace

```
Opening raw data file /home/alex/mne_data/MNE-misc-data/seeg/sample_seeg_ieeg.fif...
    Range : 1310640 ... 1370605 =   1311.411 ...  1371.411 secs
Ready.

Writing '/tmp/tmp_mne_tempdir_dhqc2o00/README'...

References
----------
Appelhoff, S., Sanderson, M., Brooks, T., Vliet, M., Quentin, R., Holdgraf, C., Chaumon, M., Mikulan, E., Tavabi, K., Höchenberger, R., Welke, D., Brunner, C., Rockhill, A., Larson, E., Gramfort, A. and Jas, M. (2019). MNE-BIDS: Organizing electrophysiological data into the BIDS format and facilitating their analysis. Journal of Open Source Software 4: (1896). https://doi.org/10.21105/joss.01896

Holdgraf, C., Appelhoff, S., Bickel, S., Bouchard, K., D'Ambrosio, S., David, O., … Hermes, D. (2019). iEEG-BIDS, extending the Brain Imaging Data Structure specification to human intracranial electrophysiology. Scientific Data, 6, 102. https://doi.org/10.1038/s41597-019-0105-7


Writing '/tmp/tmp_mne_tempdir_dhqc2o00/participants.tsv'...

participant_id	age	sex	hand
sub-sample	n/a	n/a	n/a

Writing '/tmp/tmp_mne_tempdir_dhqc2o00/participants.json'...

{
    "participant_id": {
        "Description": "Unique participant identifier"
    },
    "age": {
        "Description": "Age of the participant at time of testing",
        "Units": "years"
    },
    "sex": {
        "Description": "Biological sex of the participant",
        "Levels": {
            "F": "female",
            "M": "male"
        }
    },
    "hand": {
        "Description": "Handedness of the participant",
        "Levels": {
            "R": "right",
            "L": "left",
            "A": "ambidextrous"
        }
    }
}
Writing electrodes file to...  /tmp/tmp_mne_tempdir_dhqc2o00/sub-sample/ieeg/sub-sample_electrodes.tsv
Writing coordsytem file to...  /tmp/tmp_mne_tempdir_dhqc2o00/sub-sample/ieeg/sub-sample_coordsystem.json
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/software/anaconda3/envs/mnedev/lib/python3.9/site-packages/mne_bids/write.py", line 1402, in write_raw_bids
    _write_dig_bids(bids_path, raw, overwrite, verbose)
  File "/home/alex/software/anaconda3/envs/mnedev/lib/python3.9/site-packages/mne_bids/dig.py", line 368, in _write_dig_bids
    coordsystem_path.update(space=coord_frame)
  File "/home/alex/software/anaconda3/envs/mnedev/lib/python3.9/site-packages/mne_bids/path.py", line 726, in update
    self._check()
  File "/home/alex/software/anaconda3/envs/mnedev/lib/python3.9/site-packages/mne_bids/path.py", line 842, in _check
    raise ValueError(f'space ({space}) is not valid for '
ValueError: space (CapTrak) is not valid for datatype (ieeg).
Should be one of ['ICBM452AirSpace', 'ICBM452Warp5Space', 'IXI549Space', 'fsaverage', 'fsaverageSym', 'fsLR', 'MNIColin27', 'MNI152Lin', 'MNI152NLin2009aSym', 'MNI152NLin2009bSym', 'MNI152NLin2009cSym', 'MNI152NLin2009aAsym', 'MNI152NLin2009bAsym', 'MNI152NLin2009cAsym', 'MNI152NLin6Sym', 'MNI152NLin6ASym', 'MNI305', 'NIHPD', 'OASIS30AntsOASISAnts', 'OASIS30Atropos', 'Talairach', 'UNCInfant', 'fsaverage3', 'fsaverage4', 'fsaverage5', 'fsaverage6', 'fsaveragesym', 'UNCInfant0V21', 'UNCInfant1V21', 'UNCInfant2V21', 'UNCInfant0V22', 'UNCInfant1V22', 'UNCInfant2V22', 'UNCInfant0V23', 'UNCInfant1V23', 'UNCInfant2V23', 'Other', 'Pixels', 'ACPC']
```

**Comment by sappelhoff** [comment]
BIDS+iEEG coordinates trigger my anxiety :)

> How should intracranial electrodes in "head" coordinates be handled?

The MNE-Python `head` coordsystem is actually the Elekta/Neuromag/Megin system, which is identical with the CapTrak system.

If you really just want to save "head" coordinates, the simplest solution would maybe be to add an appropriate "space" keyword to the list of acceptable iEEG coordinate systems in BIDS: https://bids-specification.readthedocs.io/en/latest/99-appendices/08-coordinate-systems.html#ieeg-specific-coordinate-systems

cc @adam2392 who has suffered through this a lot, and can certainly help you better than I can here

for example in https://github.com/bids-standard/bids-specification/issues/747 (actually, you also chimed in @alexrockhill)

The PR I am currently preparing for BIDS may also simplify pointing to files with respect to which coordinates would need to be interpreted, see: https://github.com/bids-standard/bids-specification/pull/820

**Comment by alexrockhill** [comment]
Ambiguous in the sense of if you mix up scans that's a problem

**Comment by alexrockhill** [comment]
Hmmm so after re-reading the ieeg BIDS specification and thinking about coordinate frames for a minute I have some idea of what we could do. 

`ACPC` is the only supported coordinate frame for ieeg and in the description it says `The anatomical landmarks are determined in the individual's anatomical scan and no scaling or deformations have been applied to the individual's anatomical scan.` This is in coordinates specific to the individual, we just need a way to get from "head" to "acpc".

In the Freesurfer coordinate frame documentation (https://surfer.nmr.mgh.harvard.edu/fswiki/CoordinateSystems) it says `Talairach – coordinate center at Anterior Commisure, X to the right, Y points out of the noise, Z points out of the top of the head. This is an RAS space.`

So I think it might be as simple as applying the `trans` and then the Talairach transform and then you are in `acpc` space so we wouldn't need another coordinate system. This is reproducible as long as you have the recon and should work round trip.

Here is the process I think will work:

- Start in "head" coordinates from the raw file
- Apply the `trans` to get to "mri"
- Apply the Talairach transform to go to "acpc" space

- Read in coordinates in "acpc" space
- Apply Talairach inverse to get to "mri"
- Apply `trans` inverse to get to "head"

There are two options for doing this ASAIK: 1) have the user provide the `trans` and `talairach.xfm` files, this seems likely to lead to some confusion as not everyone will have fiducials or have an easy way to add them to their montage and the Talairach transform might not be something less experienced users will be familiar with. 2) have the user provide `subject` and `subjects_dir` and use those to estimate the `trans` and get the Talairach transform. I think this is much easier. I'll try a PR this way and we can change if this doesn't look good.

**Comment by adam2392** [comment]
> Here is the process I think will work:
> 
> * Start in "head" coordinates from the raw file
> * Apply the `trans` to get to "mri"
> * Apply the Talairach transform to go to "acpc" space
> * Read in coordinates in "acpc" space
> * Apply Talairach inverse to get to "mri"
> * Apply `trans` inverse to get to "head"

If that process is actually correct and reproducible... then I'm all for it. I'm not too familiar with the `head` space. Does the `talairach.xfm` really map surface RAS to ACPC? I thought that just maps things to MNI/fsaverage space...?

@larsoner was walking me through this a while back. I could be wrong though.

I think these extra coordinate transforms make it complicated for anyone, even someone used to the coordinate frames, so definitely a good example add to the mne-bids ieeg example would be nice.

**Comment by alexrockhill** [comment]
Sorry @adam2392, I guess I never responded to this...

"head" is a necessary evil for using MNE because it is the internal reference frame. It is defined with the origin between the LPA and RPA and z pointing up relative to the nasion. It doesn't make a whole lot of sense for ieeg because no one has fiducial points but, on the other hand, it is a well-defined coordinate frame without referencing a scan (as compared to surface RAS which is in reference to a scan; although if you were to use a different scan and freesurfer recon and try to align the fiducials to the head reconstruction, the estimate using the inverse Talairach of fsaverage fiducials is off by several cm so it would not be very useful for intracranial recordings--you would be in a completely different brain structure--and getting two people to agree on the fiducial locations is an inherently imprecise task so it does have its drawbacks too).

As I understand it, `fsaverage` is in MNI space and MNI is an ACPC based coordinate system, which I just stumbled upon when reading the Freesurfer coordinate frame documentation. So it all just happens to work out perfectly that when you transform to `fsaverage` it's ACPC-aligned.

**Comment by larsoner** [comment]
> So I think it might be as simple as applying the trans and then the Talairach transform and then you are in acpc space so we wouldn't need another coordinate system. This is reproducible as long as you have the recon and should work round trip.

You have to be careful here. The `tailarach.xfm` FreeSurfer produces takes points from the subject's MRI space to fsaverage's MRI space. This happens to be MNI, and thus happens to be ACPC, *but this is not the same as the original subject's ACPC*. While the origins should in principle be identical (as they are defined by the intersections of some anatomical structures), the `talairach.xfm` can impose scalings, rotations, and shears (full affine) that could be very wrong for a given subject.

For example, if you take a 3 month MRI like one of John Richard's templates, estimate some points in their MRI space, then apply `talairach.xfm` to them, they will *not* be in that subject's ACPC space -- they will be scaled by a factor of 2 or more away from the origin (to scale from the subject to fsaverage via `talairach.xfm`), and be way too far away to be where they should be in that subject's ACPC space.

> ACPC is the only supported coordinate frame for ieeg and in the description it says The anatomical landmarks are determined in the individual's anatomical scan and no scaling or deformations have been applied to the individual's anatomical scan.

I don't understand this. It seems to imply that the MRI must already be aligned/resampled to ACPC space. Otherwise, if it's in the native scanner space (which is in general not going to be ACPC), whatever voxels / RAS coordinates you identify for the locations are *not* going to be in that subject's ACPC space, just like they will not (in general) be in their head space, or any other space defined by some physiological landmarks.

**Comment by alexrockhill** [comment]
Yeah these are good points, this may be why @libertyh 's first step in `img_pipe` was to align to ACPC to avoid this.

Not sure if there is a great solution to that other than adding support for a coordinate frame for the MRI scanner/surface RAS space as @adam2392 had brought up. Maybe you can get AC, PC and the z-direction from the recon-all? @larsoner do you know? Then you could make a transform based on that from the head coordinate frame.

**Comment by larsoner** [comment]
I did a tiny bit of searching but I don't know unfortunately. I'd recommend searching more thoroughly, and if you don't get anything, post to the freesurfer listserv.

> this may be why @libertyh 's first step in img_pipe was to align to ACPC to avoid this.

How is it done in `img_pipe`? Some FreeSurfer command, or something else?

> ACPC is the only supported coordinate frame for ieeg and in the description it says The anatomical landmarks are determined in the individual's anatomical scan and no scaling or deformations have been applied to the individual's anatomical scan.

Are we 100% sure iEEG says coordinates are supposed to be in the subject's native ACPC space, even if the MRI that accompanies the data is not in ACPC space (I'm assuming usually it's in native scanner RAS space)? If that's the case, it seems like it would also be required to supply the scanner->ACPC transform in that case -- or equivalently, the landmarks in the native MRI (in voxels or mm) needed to determine the ACPC coordinate frame -- otherwise people have to estimate scanner->ACPC themselves and it probably won't match the one that was used by whoever made the dataset.

**Comment by alexrockhill** [comment]
> How is it done in `img_pipe`? Some FreeSurfer command, or something else?

Manually, in freeview

**Comment by alexrockhill** [comment]
> Are we 100% sure iEEG says coordinates are supposed to be in the subject's native ACPC space, even if the MRI that accompanies the data is not in ACPC space (I'm assuming usually it's in native scanner RAS space)? If that's the case, it seems like it would also be required to supply the scanner->ACPC transform in that case -- or equivalently, the landmarks in the native MRI (in voxels or mm) needed to determine the ACPC coordinate frame -- otherwise people have to estimate scanner->ACPC themselves and it probably won't match the one that was used by whoever made the dataset.

They can be in `fsaverage` space and I had thought previously that that was sub-optimal as you would want them in individual brain space, but maybe that is the best-defined coordinate frame to store them in and we should just focus on how to invert and get the coordinates back in subject-specific space from `fsaverage`. Seems a bit roundabout though...

**Comment by larsoner** [comment]
> They can be in fsaverage space 

This is an okay workaround, but doesn't really answer my core question, though -- how are sensor coordinates in a subject's own space (ACPC if it's required by the spec) meant to be used properly? We should understand this first before proceeding with what seems to be incomplete information, or resorting to transforming to `fsaverage` / `MNI` space. Can you look into how this subject's space ACPC definition is supposed to be created/used/stored? It seems like something is wrong with requiring people to put sensor coordinates in this space without *also* requiring them to define how to get from the native MRI space to that space...

**Comment by alexrockhill** [comment]
I can look into it more and maybe I'm misunderstanding you but my interpretation is that the ACPC space was chosen because you could take any scan, align it to ACPC and compute a transformation. This would be by eye as in the process described here https://www.frontiersin.org/articles/10.3389/fninf.2017.00062/full.

**Comment by larsoner** [comment]
> the ACPC space was chosen because you could take any scan, align it to ACPC and compute a transformation. 

Okay let's think through a hypothetical. You as the dataset collector start out with an MRI in its native space. You estimate the transformation to ACPC space (and resample the MRI if you want) and click-and-pick electrode locations in that space (or get them in the native space and transform, equivalently). You then upload just the original native-space MRI as part of your BIDS dataset, plus the electrode locations in the your-estimated-ACPC space, without any other information about how to get from the native MRI to that space, other than knowledge that you estimated the locations of some anatomical landmarks to get there.

I as a dataset consumer/downloader am then expected to do the same process of anatomical landmark estimation and transformation? I'm likely (almost guaranteed) to off by some mm and degrees from the translation + rotation you used to get to this space, because my definition and your definition of the anatomical landmarks that define ACPC will tend to disagree by some millimeters (e.g., 1 < diff < 10 mm in each dimension), right?

After this, to get the locations of electrodes in the native MRI space (which is the only MRI I have), I have to apply the inverse of *my* native->ACPC transformation, rather than yours, which introduces errors that could be entirely avoided if I knew your transformation from native MRI to ACPC space.

It thus seems like a strange oversight to me that the landmarks that define ACPC in the native MRI space -- or equivalently the transformation from native space to ACPC space -- are not *required* to be included if you choose to define you electrodes in this space. It seems so trivial to require their inclusion to avoid this information loss / source of error... hence why it seems like we must be missing something.

I haven't read through the iEEG BIDS paper, though, so I might totally be missing something here!

**Comment by larsoner** [comment]
... by analogy, this would be equivalent to giving people electrode locations in head coordinates, plus fiducials, plus an MRI, but not providing them with the MRI fiducials. People can estimate on their own where LPA/Nasion/RPA are and thus get from head to MRI if they want, but you and I each carrying out this task separately will estimate these differently, and hence lead to errors. The fix to avoid this error is to provide the mapping from head to MRI (by analogy, native to ACPC space for the iEEG case) to avoid any disagreement about that space's relative origin and orientation based on disagreement (mis-estimation) of the landmarks that define it...

**Comment by alexrockhill** [comment]
I was not on that paper and I follow your logic and I think it's sound, I just think that you are correct and that this is a deficiency in the BIDS standard that to my knowledge has just been handled historically by sharing the MRI resampled to ACPC space although it would make much more sense to require the transformation matrix.

**Comment by larsoner** [comment]
Sharing the MRI resampled to ACPC would be fine, too. What I wouldn't understand in sharing the native MRI but not the resampled MRI *or* the transformation *or* the landmarks that allow you to determine the transformation.

In any case, I would not rely on the `talxfm` to give you subject-specific ACPC coords, because it gives you MNI coords that are in ACPC space for `fsaverage` and MNI, not for the subject. So for the purposes of this issue maybe it's enough to just ignore subject-ACPC altogether and instead save coordinates in fsaverage/MNI space, and also provide the transformation to get back to the subject's native MRI space (i.e., `talxfm`)? That seems lossless in terms of information.

**Comment by alexrockhill** [comment]
Sounds good to me, that's what's in the current PR, I think maybe the narrative should just be adjusted

**Comment by alexrockhill** [comment]
I almost forgot...

After thinking about this, we could take the origin of the Talairach transform and then get unit vectors in each dimension and go forward left and right until we get the nasion, LPA and RPA by intersecting the `seghead` for instance. This is an algorithmic approach to defining the scan to ACPC transform but if it's not used there is no way to recover the `trans` so I still think it doesn't solve the underlying issue and the simplest solution is @adam2392 's PR one that defines coordinates in terms of voxels in a scan with a reference to that scan file.
