### ISSUE TITLE
Enable BTi handling

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#86]
MEG data in the BTi format needs a lot of work in the BIDS environment.

1. It needs to be supported by the BIDS-validator, see: https://github.com/INCF/bids-validator/issues/553

2. We need a working example properly formatted in BIDS to be able to compare against it: https://github.com/INCF/BIDS-examples/issues/121

3. We need to properly copy BTi data within `raw_to_bids` (e.g., by writing a `copyfile_bti` function, but not necessarily)

Once we have that, we can fix this:

https://github.com/mne-tools/mne-bids/blob/63ad342b30248ee4a24c73de7398afe3570309fa/mne_bids/tests/test_mne_bids.py#L135-L140

**Comment by monkeyman192** [comment]
[This](http://www.fieldtriptoolbox.org/getting_started/bti) is probably a good place to start as reference.
Looking at some BTi data I have from the HCP, I don't exactly see why we need a separate function to copy the BTi data specifically. Surely the way data would be copied currently (plus #77 with some modification probably) would be sufficient.
We would also need to modify the [_parse_ext](https://github.com/mne-tools/mne-bids/blob/master/mne_bids/io.py#L15-L24) function so that it doesn't return the weird file types that it might (eg. a file called `e,rfhp1.0Hz,COH` will have the extension `.0Hz,COH`) (side note: I think that specifying the extension as `.pdf` by default should probably be changed/removed. It should be fine to have files with no extension...)

**Comment by sappelhoff** [comment]
> I don't exactly see why we need a separate function to copy the BTi data specifically.

I agree and edited the issue

> I think that specifying the extension as .pdf by default should probably be changed/removed

You mean within MNE-Python? :-) +1

**Comment by jasmainak** [comment]
Is this still an issue?

**Comment by sappelhoff** [comment]
issue 1. in the original post has been solved, I am not sure about 3. ... and for 2. I opened an issue here: https://github.com/bids-standard/bids-examples/issues/121

So ... we need to confirm 2. and then can either close or fix
