### ISSUE TITLE
 module 'mne.chpi' has no attribute 'get_chpi_info'

### ISSUE THREAD

**Issue by nikitaagarwala16** [mne-tools/mne-bids#871]
#### Describe the bug
Getting this error on writing some raw data to bids

#### Steps to reproduce

```python
out_path = pathlib.Path('out_data/sample_BIDS')

bids_path = mne_bids.BIDSPath(subject='01',
                              session='01',
                              task='audiovisual',
                              run='01',
                              root=out_path)

mne_bids.write_raw_bids(raw, bids_path=bids_path, events_data=events,
                        event_id=event_id, overwrite=True)
```
#### Expected results
All expected files should have been added in out_data

#### Actual results

Getting the following AttributeError: module 'mne.chpi' has no attribute 'get_chpi_info

**Comment by hoechenberger** [comment]
Hello @nikitaagarwala16,

which versions of MNE-BIDS and MNE-Python do you use?

**Comment by nikitaagarwala16** [comment]
Hello @hoechenberger,
I am currently using MNE- Python version --> '0.23.3' 
and for MNE-BIDS --->'0.8'

**Comment by hoechenberger** [comment]
Thank you, I will take a look!

**Comment by PelinGenc1980** [comment]
Hello, 
I have the same issue.
Is there any solution for that?

**Comment by hoechenberger** [comment]
Hello @PelinGenc1980 and @nikitaagarwala16,

the respective function, `get_chpi_info`, was only added in the latest development branch of MNE-Python (I'm actually not sure how our tests in MNE-BIDS passed CI, since we test against development **and** stable branch)

The quick solution is to update your MNE-Python version to the development branch

```
pip install -U https://github.com/mne-tools/mne-python/archive/refs/heads/main.zip
```

@sappelhoff Do you think it's worthwhile to fix this in MNE-BIDS? Otherwise we can just wait until MNE-Python 0.24 is released (few more weeks??)…

**Comment by sappelhoff** [comment]
I think we can wait a few more weeks. :)

**Comment by PelinGenc1980** [comment]
Hello @hoechenberger,

> pip install -U https://github.com/mne-tools/mne-python/archive/refs/heads/main.zip
> ```

Unfortunatelly, it didn't fix my problem. I'm still getting the same error.

**Comment by hoechenberger** [comment]
It **should** work though. Did you restart your Python interpreter after updating MNE?

**Comment by PelinGenc1980** [comment]
Oh yes, I did. Now it gives another error.

It cannot retrieve the storage location of the sample data and gives this error:
RuntimeError: For dataset downloading to work, the pooch module is needed, but it could not be imported.

But adding the pooch module doesn't eliminate the error.

**Comment by hoechenberger** [comment]
Pooch also depends on `tqdm`, so be sure to install this one as well :)

**Comment by PelinGenc1980** [comment]
Hello @hoechenberger,

I am doing your tutorial on youtube "Pybrain: M/EEG analysis with MNE Python" and have a problem at the very beginning.

After updating MNE-Python version (to solve the error: module 'mne.chpi' has no attribute 'get_chpi_info),
now retrieving the sample data doesn't work any more. As I said previously, it gives "No module named 'pooch'" error. Installing tqdm before installing pooch also didn't help.

Is there any other way to retrieve the storage location of the sample data instead of this line:
sample_data_dir = mne.datasets.sample.data_path()

**Comment by ilyak93** [comment]
It gives me the same issue @PelinGenc1980 wrote about, tqdm installed.
