### ISSUE TITLE
Supported Python versions: CI test matrix getting too big

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#933]
Hello,

now that Python 3.10 is out, we'll need to add it to our CI tests.

The test matrix is already huge, any suggestions what we could do about this?

Ideas:

- simply drop support for Python 3.7
- run tests with `mne-python:main` only on the latest Python version

Thoughts?

**Comment by sappelhoff** [comment]
I like your second suggestion :+1:

**Comment by larsoner** [comment]
Another option is not to test every version, but just the oldest and newest (here, 3.7 and 3.10). We've skipped in-between versions in MNE-Python and never hit an issue from it at least. (The only reason we don't currently test just 3.7 and 3.10 there is for example because VTK isn't available on Windows for 3.10 yet, so the highest we can do on Windows is 3.9.) I think if you're writing a library where you have Cython or some compiled C code you probably need all of them, but given the stability and deprecation policies of the Python versions, just doing 3.7 and 3.10 is probably fine.
