### ISSUE TITLE
Add 3D figure rendering to documentation

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids#981]
> we don't support pyvista and 3D plots in the doc of mne-bids... to be done later I guess

_Originally posted by @agramfort in https://github.com/mne-tools/mne-bids/pull/980#pullrequestreview-902638616_

cc @larsoner

**Comment by larsoner** [comment]
Adding a scraper for `plot_alignment` or other things that just use a simple 3D scene is as simple as adding `'image_scrapers': ('pyvista', ...)` to `sphinx_gallery-conf` in principle. In practice you then need to make sure it actually renders properly.

If you want `stc.plot` or something, you want `_BrainScraper` or so, but it's still doable.

I'd wait until you had a use case, then I'm happy to help. It sounds like you can't actually use it for #980 because you don't have the right files (?).

**Comment by sappelhoff** [comment]
Do we still need this? Where are we missing a 3D figure in our docs?

This was the example worked on in #980: https://mne.tools/mne-bids/stable/auto_examples/convert_ieeg_to_bids.html#sphx-glr-auto-examples-convert-ieeg-to-bids-py

looks fine to me? I'd close this issue.
